settings.python.uv_venv_auto = true

[tools]
uv = "latest"
deno = "latest"
watchexec = "latest"

[tasks."dev:flask"]
description = "Start a dev server"
run = "uv run flask --app cnc.main:app run --host=0.0.0.0 --port=5500"

[tasks."dev:stop"]
description = "Force stop the dev server"
run = 'pkill watchexec ; pkill -f "mise watch"'

[tasks.dev]
description = "Start a dev server and reload on changes"
run = "MISE_JOBS=1 mise watch --restart --wrap-process=session build ::: dev:flask"

[tasks.build]
description = "Build static files without starting the server"
quiet = true
run = "uv run cnc-build"

[tasks.pyright]
description = "Run type checks on Python"
run = "uv run pyright --project ."

[tasks.checkjs]
description = "Run type checks on JavaScript"
run = "deno check --allow-import graph.js"

[tasks.fetch-hive]
description = "Fetch and cache Hive game data"
run = "uv run src/cnc/fetch_hive_games.py"

[tasks.fetch-hive-force]
description = "Force refresh all Hive game data"
run = "uv run src/cnc/fetch_hive_games.py --force"
