[tools]
uv = "latest"

[tasks.dev]
description = "Start a dev server"
quiet = true
run = "uv run flask run --debug"

[tasks.build]
description = "Build static files without starting the server"
quiet = true
run = "uv run app.py"
