settings.python.uv_venv_auto = true

[tools]
uv = "latest"
deno = "latest"
watchexec = "latest"
fd = "latest"

[tasks."dev:flask"]
description = "Start a dev server"
run = "uv run flask --app cnc.main:app run --host=0.0.0.0 --port=5500"

[tasks."dev"]
run = """
  watchexec --restart --debounce 500ms --no-meta 'lsof -ti:5500 | xargs kill -9; mise build; mise dev:flask'
"""

[tasks.build]
description = "Build static files without starting the server"
quiet = true
run = "uv run cnc-build"

[tasks.pyright]
description = "Run type checks on Python"
run = "uv run pyright --project ."

[tasks.checkjs]
description = "Run type checks on JavaScript"
run = "deno check --allow-import graph.js"

[tasks.fetch-hive]
description = "Fetch and cache Hive game data"
run = "uv run src/cnc/hive/fetch_hive_games.py"

[tasks.fetch-hive-force]
description = "Force refresh all Hive game data"
run = "uv run src/cnc/hive/fetch_hive_games.py --force"

[tasks."db:schema"]
description = "Show the current database schema"
run = "cat src/cnc/hive/schema.sql"

[tasks."db:validate"]
description = "Validate SQL schema syntax"
run = "scripts/validate_schema.py"

[tasks."dev:status"]
description = "Check what's running on the dev port"
run = "lsof -i :5500 || echo 'Nothing running on port 5500'"

[tasks."dev:logs"]
description = "Show logs from the dev server process"
run = "ps aux | grep 'dev_server.py' | grep -v grep || echo 'No dev server process found'"

[tasks."dev:clean"]
description = "Clean up all dev server processes and start fresh"
run = "mise run dev:stop && sleep 1 && mise run dev"

[tasks."find-unused-code"]
description = "Find unused methods/functions"
run = "uvx vulture src/ | rg 'method|function'"

[tasks."add-license"]
description = "Add CC0 license headers to source files"
tools."go:github.com/google/addlicense" = "latest"
run = """
  fd -t f . -X addlicense -c "Emily" -l cc0 -f license-header.txt {}
"""
