settings.python.uv_venv_auto = true

[tools]
uv = "latest"
watchexec = "latest"
fd = "latest"

[tasks."dev"]
run = """
  watchexec --restart --debounce 500ms --no-meta 'lsof -ti:5500 | xargs kill -9; mise build; mise dev:flask'
"""

[tasks."dev:next"]
description = "Start Next.js development server with HMR"
run = "pnpm exec next dev --port 3000"

[tasks."build:data"]
description = "Build data used by the Next.js app"
sources = [
  "data/",
  "public/",
  "scripts/",
  "src/",
  "static/",
  "pyproject.toml",
  "uv.lock",
]
outputs = ["build/data/hive-data.json"]
run = "uv run src/cnc/main.py"

[tasks.build]
description = "Build the site"
quiet = true
depends = ["build:data"]
run = "pnpm exec next build --turbopack"

[tasks."serve"]
description = "Serve statically built site"
run = "uv run python -m http.server 5500 --directory build/"

[tasks.check]
description = "Run all checks"
depends = ["check:*"]

[tasks."check:pyright"]
description = "Run type checks on Python"
run = "uv run pyright --project ."

[tasks."check:ts"]
description = "Run type checks on TypeScript"
run = "pnpm exec tsc --noEmit"

[tasks.fetch-hive]
description = "Fetch and cache Hive game data"
run = "uv run src/cnc/hive/fetch_hive_games.py"

[tasks.fetch-hive-force]
description = "Force refresh all Hive game data"
run = "uv run src/cnc/hive/fetch_hive_games.py --force"

[tasks."db:schema"]
description = "Show the current database schema"
run = "cat src/cnc/hive/schema.sql"

[tasks."db:validate"]
description = "Validate SQL schema syntax"
run = "scripts/validate_schema.py"

[tasks."dev:status"]
description = "Check what's running on the dev port"
run = "lsof -i :5500 || echo 'Nothing running on port 5500'"

[tasks."dev:logs"]
description = "Show logs from the dev server process"
run = "ps aux | grep 'dev_server.py' | grep -v grep || echo 'No dev server process found'"

[tasks."dev:clean"]
description = "Clean up all dev server processes and start fresh"
run = "mise run dev:stop && sleep 1 && mise run dev"

[tasks."find-unused-code"]
description = "Find unused methods/functions"
run = "uvx vulture src/ | rg 'method|function'"

[tasks."add-license"]
description = "Add CC0 license headers to source files"
tools."go:github.com/google/addlicense" = "latest"
run = """
  fd -t f . -X addlicense -c "Emily" -l cc0 -f license-header.txt {}
"""
