settings.python.uv_venv_auto = true

[tools]
uv = "latest"
watchexec = "latest"
fd = "latest"
dprint = "latest"

[tasks.build]
description = "Build the site"
quiet = true
run = "pnpm exec next build --turbopack"

[tasks."serve"]
description = "Serve statically built site"
run = "uv run python -m http.server 5500 --directory build/"

[tasks.check]
description = "Run all checks"
depends = ["check:*"]

[tasks."check:pyright"]
description = "Run type checks on Python"
run = "uv run pyright --project ."

[tasks."check:ts"]
description = "Run type checks on TypeScript"
run = "pnpm exec tsc --noEmit"

[tasks."fmt"]
description = "Format code"
run = "dprint fmt"

[tasks.test]
description = "Run unit tests (Vitest)"
run = "pnpm exec vitest run"

[tasks."test:watch"]
description = "Run unit tests in watch mode"
run = "pnpm exec vitest"

[tasks."test:coverage"]
description = "Run unit tests with coverage"
run = "pnpm exec vitest run --coverage"

[tasks.fetch-hive]
description = "Fetch and cache Hive game data"
run = "uv run src/cnc/hive/fetch_hive_games.py"

[tasks."fetch-hive:force"]
description = "Force refresh all Hive game data"
run = "uv run src/cnc/hive/fetch_hive_games.py --max-age=0"

[tasks."fetch-hive:ignore-cache"]
description = "Don't load the cache even, just redownload all Hive game data"
run = "uv run src/cnc/hive/fetch_hive_games.py --force"

[tasks."db:schema"]
description = "Show the current database schema"
run = "cat src/cnc/hive/schema.sql"

[tasks."db:validate"]
description = "Validate SQL schema syntax"
run = "scripts/validate_schema.py"

[tasks."dev"]
description = "Start Next.js development server with HMR at http://localhost:3000/cnc/"
run = "pnpm exec next dev --port 3000" # not using turbopack because of https://github.com/tailwindlabs/tailwindcss/issues/15876

[tasks."find-unused-code"]
description = "Find unused methods/functions"
run = "uvx vulture src/ | rg 'method|function'"

[tasks."add-license"]
description = "Add CC0 license headers to source files"
tools."go:github.com/google/addlicense" = "latest"
run = """
  fd -t f . -X addlicense -c "Emily" -l cc0 -f license-header.txt {}
"""

[tasks."shadcn"]
description = "Call the shadcn CLI"
run = "pnpm dlx shadcn@latest"
